<a href="https://colab.research.google.com/github/ssrbazpur/Data-Science/blob/master/Python_Data_Science_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
import pandas as pd

In [0]:
df=pd.read_csv("/content/drive/My Drive/Data Science/mercedesbenz.csv")

In [4]:
df.head()

   ID       y  X0 X1  X2 X3 X4  ... X378 X379 X380  X382  X383  X384  X385
0   0  130.81   k  v  at  a  d  ...    0    0    0     0     0     0     0
1   6   88.53   k  t  av  e  d  ...    0    0    0     0     0     0     0
2   7   76.26  az  w   n  c  d  ...    0    0    0     1     0     0     0
3   9   80.62  az  t   n  f  d  ...    0    0    0     0     0     0     0
4  13   78.02  az  v   n  f  d  ...    0    0    0     0     0     0     0

[5 rows x 378 columns]

In [5]:
df.shape

(4209, 378)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [7]:
df.describe()

                ID            y  ...         X384         X385
count  4209.000000  4209.000000  ...  4209.000000  4209.000000
mean   4205.960798   100.669318  ...     0.000475     0.001426
std    2437.608688    12.679381  ...     0.021796     0.037734
min       0.000000    72.110000  ...     0.000000     0.000000
25%    2095.000000    90.820000  ...     0.000000     0.000000
50%    4220.000000    99.150000  ...     0.000000     0.000000
75%    6314.000000   109.010000  ...     0.000000     0.000000
max    8417.000000   265.320000  ...     1.000000     1.000000

[8 rows x 370 columns]

<p> Only integer feature will be taken categorial is not to be used while training</p>

In [9]:
#Finding no of categories in X0
df['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
am     18
i      18
aq     18
u      17
aw     16
l      16
ad     14
k      11
b      11
au     11
r      10
as     10
bc      6
ao      4
c       3
q       2
aa      2
g       1
ac      1
ab      1
Name: X0, dtype: int64

In [10]:
df[df['y']>20]

        ID       y  X0 X1  X2 X3 X4  ... X378 X379 X380  X382  X383  X384  X385
0        0  130.81   k  v  at  a  d  ...    0    0    0     0     0     0     0
1        6   88.53   k  t  av  e  d  ...    0    0    0     0     0     0     0
2        7   76.26  az  w   n  c  d  ...    0    0    0     1     0     0     0
3        9   80.62  az  t   n  f  d  ...    0    0    0     0     0     0     0
4       13   78.02  az  v   n  f  d  ...    0    0    0     0     0     0     0
...    ...     ...  .. ..  .. .. ..  ...  ...  ...  ...   ...   ...   ...   ...
4204  8405  107.39  ak  s  as  c  d  ...    0    0    0     0     0     0     0
4205  8406  108.77   j  o   t  d  d  ...    0    0    0     0     0     0     0
4206  8412  109.22  ak  v   r  a  d  ...    0    0    0     0     0     0     0
4207  8415   87.48  al  r   e  f  d  ...    0    0    0     0     0     0     0
4208  8417  110.85   z  r  ae  c  d  ...    0    0    0     0     0     0     0

[4209 rows x 378 columns]

<p> CSV FILES </p>

In [0]:
from io import StringIO

In [0]:
data=('col1,col2,col3\n1,2,3\n4,5,6')

In [14]:
type(data)

str

In [16]:
pd.read_csv(StringIO(data))

   col1  col2  col3
0     1     2     3
1     4     5     6

In [19]:
#Using only specified columns
df=pd.read_csv(StringIO(data),usecols=['col1','col2'])
df

   col1  col2
0     1     2
1     4     5

In [20]:
df['col1']

0    1
1    4
Name: col1, dtype: int64

In [21]:
df['col1'][1]

4

In [0]:
df=pd.read_csv(StringIO(data),usecols=['col1','col2','col3'],index_col=1)
#index column 1

In [24]:
df

      col1  col3
col2
2        1     3
5        4     6